export enum OrganizationRole {
  RETAIL_PHARMACY = 'RETAIL_PHARMACY',
  PHARMACEUTICAL_SUPPLIER = 'PHARMACEUTICAL_SUPPLIER',
  COSMETICS_SUPPLIER = 'COSMETICS_SUPPLIER',
  HOSPITAL_PHARMACY = 'HOSPITAL_PHARMACY',
  OTHER = 'OTHER'
}
